name: config-consistency

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify standard configs
        shell: bash
        run: |
          set -euo pipefail
          files=(
            ".gitignore"
            ".gitattributes"
            ".eslintrc.json"
            ".prettierrc"
            ".vscode/settings.json"
            ".vscode/extensions.json"
          )
          for f in "${files[@]}"; do
            if [ -f "$f" ] && [ -f ".github/standard-configs/${f##*/}" ]; then
              if ! diff -u ".github/standard-configs/${f##*/}" "$f"; then
                echo "::error file=$f::$f differs from standard"
                exit 1
              fi
            fi
          done
